---
all:
  hosts:
    sonar-01:
      ansible_host: 178.154.200.93
    nexus-01:
      ansible_host: 178.154.205.189
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: parcamiko
    ansible_user: centos